version: 2.1
  jobs:
    build:
      docker:
        - image: circleci/php:7.3-cli
      steps:
        - checkout
        - run: composer install -n --prefer-dist
        - run: ./vendor/bin/phpunit
        - store_test_results:
            path: tests/_output
        - store_artifacts:
            path: tests/_output
